name: Build and Deploy Ngx-translation-editor

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Checkout Repository
    uses: actions/checkout@v2

  - name: Adding Node.js
    uses: actions/setup-node@v2
    with:
      node-version: 20.9

  - name: Install Dependencies
      run: npm install

  - name: Build Angular App
      run: npm run build

  - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/ngx-translation-editor/browser
      env:
        CI: true
        GH_TOKEN: ${{ secrets.PUBLISH_GH_PAGE }}