name: Build and Deploy Ngx-translation-editor

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.9

      - name: Install Angular global
        run: npm install -g @angular/cli@17.3.4

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npx ng build --base-href /ngx-translation-editor/

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/ngx-translation-editor/browser --name="Denis Micheletti" --email=denis.micheletti@gmail.com --no-silent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.PUBLISH_GH_PAGE }}
